require "payments/client/operations/http"
require "payments/client/operations/merchants"
require "payments/client/operations/financial_contexts"
require "payments/client/operations/receipt_numbers"
require "payments/client/operations/pricing_schedule"
require "payments/client/operations/settlements"
